### ISSUE TITLE
Issue with the evaluation

### ISSUE THREAD

**Issue by thatbirdguythatuknownot** [neogeny/late#4]
The default value doesn't evaluate in the expected late-bound way.
```py
@latebinding
def f(x: list[list[Any]] = __([[]])) -> list[list[Any]]:
    x[0].append(1)
    return x

assert f() == [[1]]
assert f() == [[1]] # fails; f() returns [[1, 1]] instead
```

```py
t = 0

def a() -> int:
    global t # for demonstration purposes
    t += 1
    return t

@latebinding
def f(x: int = __(a())) -> int:
    return 2 * x

assert f() == 2
assert f() == 4 # fails; f() returns 2 instead
```
I am aware the second one could just use a generator, but it's still a bit unexpected. The first one is still a problem though.

**Comment by apalala** [comment]
On:

```python
def f(x: list[list[Any]] = __([[]])) -> list[list[Any]]:
```
The problem is that the inner list constructor is not managed by *Late*.  

It's possible to make the late binding by `__()` attempt recursion, because `__()` is called only once. 

I'll keep this issue open to think about that.

**Comment by apalala** [comment]
On:

```python
@latebinding
def f(x: int = __(a())) -> int:
```

The problem is that `a()` is _not_ a generator. This would work:

```python
def a() -> Iterator[int]:
    global t # for demonstration purposes
    t += 1
    yield t
```

Another option is to have `__()` identify function values to be invoked on each call, something like:

```python
@latebinding
def f(x: int = __(a)) -> int:
 ```

I'll also think about this.
